site: Amir's personal website
title: Amir's personal website
greetings: hey 👋
lang: en-US
data-theme: dark # default theme "dark" | "light"

author:
  name: Amir
  bio:  
  description:
  username: # general username
  github: ax00z # github username
  email: aranjbar@ryerson.ca # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "ax00z.github.io" # Domain Name of host. [username].github.io for github pages
permalink: pretty


# local
# url: "http://localhost:4000" # 
# baseurl: "/project" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: false
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
site: Amir's personal website
title: Amir's personal website
greetings: hey 👋
lang: en-US
data-theme: dark # default theme "dark" | "light"

author:
  name: Amir
  bio:  
  description: I'm amir, currently a cs undergrad and passionate about everything software related
  username: # general username
  github: ax00z # github username
  email: aranjbar@ryerson.ca # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://ax00z.github.io" # Domain Name of host. [username].github.io for github pages
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: false
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
